import { viteBundler } from '@vuepress/bundler-vite'
import { defineUserConfig } from 'vuepress'
import { plumeTheme } from 'vuepress-theme-plume'
import { pseudocodeLanguage } from './pseudocode.js'

const paperAbbreviations = {
  'Ama17': '"Amazon EC2 P3 Instances." 2017. [Link](https://aws.amazon.com/ec2/instance-types/p3/)',
  'Ten17': '"Tensorflow graph transform creates corrupted graph." 2017. [Link](https://github.com/tensorflow/tensorflow/issues/7523)',
  'XLA17': '"XLA: Optimizing Compiler for TensorFlow." 2017. [Link](https://www.tensorflow.org/xla)',
  'Gra18': '"Graph transform: fold constant with invalid graph." 2018. [Link](https://github.com/tensorflow/tensorflow/issues/16545)',
  'Ten18': '"Tensor Cores in NVIDIA Volta Architecture." 2018. [Link](https://www.nvidia.com/en-us/data-center/tensorcore/)',
  'Aba16': 'Martín Abadi, Paul Barham, Jianmin Chen, Zhifeng Chen, Andy Davis, Jeffrey Dean, Matthieu Devin, Sanjay Ghemawat, Geoffrey Irving, Michael Isard, Manjunath Kudlur, Josh Levenberg, Rajat Monga, Sherry Moore, Derek G Murray, Benoit Steiner, Paul Tucker, Vijay Vasudevan, Pete Warden, Martin Wicke, Yuan Yu, Xiaoqiang Zheng. "TensorFlow: A System for Large-Scale Machine Learning." Proceedings of the 12th USENIX Conference on Operating Systems Design and Implementation (OSDI). 2016.',
  'Ban06': 'Sorav Bansal, Alex Aiken. "Automatic Generation of Peephole Superoptimizers." Proceedings of the 12th International Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS XII). 2006.',
  'Che18': 'Tianqi Chen, Thierry Moreau, Ziheng Jiang, Haichen Shen, Eddie Q Yan, Leyuan Wang, Yuwei Hu, Luis Ceze, Carlos Guestrin, Arvind Krishnamurthy. "TVM: End-to-End Optimization Stack for Deep Learning." 2018. [Link](http://arxiv.org/abs/1802.04799)',
  'Che18a': 'Tianqi Chen, Lianmin Zheng, Eddie Yan, Ziheng Jiang, Thierry Moreau, Luis Ceze, Carlos Guestrin, Arvind Krishnamurthy. "Learning to Optimize Tensor Programs." Advances in Neural Information Processing Systems. 2018.',
  'Che14': 'Sharan Chetlur, Cliff Woolley, Philippe Vandermersch, Jonathan Cohen, John Tran, Bryan Catanzaro, Evan Shelhamer. "cuDNN: Efficient Primitives for Deep Learning." 2014. [Link](http://arxiv.org/abs/1410.0759)',
  'Chu19': 'Berkeley R Churchill, Oded Padon, Rahul Sharma, Alex Aiken. "Semantic Program Alignment for Equivalence Checking." Proceedings of the 2019 ACM SIGPLAN Conference on Programming Language Design and Implementation (PLDI). June 22-26, 2019. [Link](https://doi.org/10.1145/3314221.3314596)',
  'Cub16': 'Cublas. "Dense Linear Algebra on GPUs." 2016. [Link](https://developer.nvidia.com/cublas)',
  'Dah17': 'Manjeet Dahiya, Sorav Bansal. "Black-Box Equivalence Checking Across Compiler Optimizations." Programming Languages and Systems. 2017.',
  'DeM08': 'Leonardo De Moura, Nikolaj Bjørner. "Z3: An Efficient SMT Solver." Proceedings of the Theory and Practice of Software, 14th International Conference on Tools and Algorithms for the Construction and Analysis of Systems (TACAS\'08/ETAPS\'08). 2008.',
  'Dev18': 'Jacob Devlin, Ming-Wei Chang, Kenton Lee, Kristina Toutanova. "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding." 2018.',
  'Dum16': 'Vincent Dumoulin, Francesco Visin. "A guide to convolution arithmetic for deep learning." CoRR. 2016.',
  'Gul03': 'Sumit Gulwani, George C Necula. "Discovering Affine Equalities Using Random Interpretation." Proceedings of the 30th ACM SIGPLAN-SIGACT Symposium on Principles of Programming Languages (POPL \'03). 2003.',
  'He16': 'Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun. "Deep residual learning for image recognition." Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition (CVPR). 2016.',
  'How17': 'Andrew G Howard, Menglong Zhu, Bo Chen, Dmitry Kalenichenko, Weijun Wang, Tobias Weyand, Marco Andreetto, Hartwig Adam. "MobileNets: Efficient Convolutional Neural Networks for Mobile Vision Applications." 2017.',
  'Jia18': 'Zhihao Jia, Sina Lin, Charles R Qi, Alex Aiken. "Exploring Hidden Dimensions in Accelerating Convolutional Neural Networks." Proceedings of the 35th International Conference on Machine Learning (Proceedings of Machine Learning Research). 2018.',
  'Jia19': 'Zhihao Jia, James Thomas, Todd Warzawski, Mingyu Gao, Matei Zaharia, Alex Aiken. "Optimizing DNN Computation with Relaxed Graph Substitutions." Proceedings of the 2nd Conference on Systems and Machine Learning (SysML\'19). 2019.',
  'Jia19a': 'Zhihao Jia, Matei Zaharia, Alex Aiken. "Beyond Data and Model Parallelism for Deep Neural Networks." Proceedings of the 2nd Conference on Systems and Machine Learning (SysML\'19). 2019.',
  'Le14': 'Mehrdad Vu Le, Zhendong Afshari, Su. "Compiler validation via equivalence modulo inputs." ACM SIGPLAN Conference on Programming Language Design and Implementation. 2014. June 09 -11, 2014. [Link](https://doi.org/10.1145/2594291.2594334)',
  'Li16': 'Chao Li, Yi Yang, Min Feng, Srimat Chakradhar, Huiyang Zhou. "Optimizing memory efficiency for deep convolutional neural networks on GPUs." Proceedings of the International Conference for High Performance Computing, Networking, Storage and Analysis. 2016.',
  'Mas87': 'Henry Massalin. "Superoptimizer: a look at the smallest program." ACM SIGARCH Computer Architecture News. 1987.',
  'Mir17': 'Azalia Mirhoseini, Hieu Pham, Quoc V Le, Benoit Steiner, Rasmus Larsen, Yuefeng Zhou, Naveen Kumar, Mohammad Norouzi, Samy Bengio, and Jeff Dean. "Device Placement Optimization with Reinforcement Learning." 2017.',
  'Mkl16': 'Mkldnn. "Intel Math Kernel Library for Deep Neural Networks." 2016. [Link](https://01.org/mkl-dnn)',
  'Nai10': 'Vinod Nair, Geoffrey E Hinton. "Rectified Linear Units Improve Restricted Boltzmann Machines." Proceedings of the 27th International Conference on International Conference on Machine Learning (ICML\'10). 2010. [Link](http://dl.acm.org/citation.cfm?id=3104322.3104425)',
  'Nec00': 'George C Necula. "Translation validation for an optimizing compiler." Proceedings of the 2000 ACM SIGPLAN Conference on Programming Language Design and Implementation (PLDI), Vancouver. 2000. June 18-21, 2000. [Link](https://doi.org/10.1145/349299.349314)',
  'Pnu98': 'Amir Pnueli, Michael Siegel, Eli Singerman. "Translation Validation." Tools and Algorithms for Construction and Analysis of Systems, 4th International Conference, TACAS \'98, Held as Part of the European Joint Conferences on the Theory and Practice of Software, ETAPS\'98. 1998. March 28 -April 4, 1998. [Link](https://doi.org/10.1007/BFb0054170)',
  'PyT17': 'Pytorch. "Tensors and Dynamic neural networks in Python with strong GPU acceleration." 2017. [Link](https://pytorch.org)',
  'Rus15': 'Olga Russakovsky, Jia Deng, Hao Su, Jonathan Krause, Sanjeev Satheesh, Sean Ma, Zhiheng Huang, Andrej Karpathy, Aditya Khosla, Michael Bernstein, Alexander C Berg, Li Fei-Fei. "ImageNet Large Scale Visual Recognition Challenge." International Journal of Computer Vision. 2015. [Link](https://doi.org/10.1007/s11263-015-0816-y)',
  'Sha13': 'Rahul Sharma, Eric Schkufza, Berkeley R Churchill, Alex Aiken. "Data-driven equivalence checking." Proceedings of the 2013 ACM SIGPLAN International Conference on Object Oriented Programming Systems Languages & Applications, OOPSLA 2013, part of SPLASH 2013. October 26-31, 2013. [Link](https://doi.org/10.1145/2509136.2509509)',
  'Siv19': 'Muthian Sivathanu, Tapan Chugh, Sanjay S Singapuram, Lidong Zhou. "Astra: Exploiting Predictability to Optimize Deep Learning." Proceedings of the Twenty-Fourth International Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS \'19). 2019.',
  'Tat11': 'Ross Tate, Michael Stepp, Zachary Tatlock, Sorin Lerner. "Equality Saturation: A New Approach to Optimization." Logical Methods in Computer Science. 2011. [Link](https://doi.org/10.2168/LMCS-7(1:10)2011)',
  'Ten17a': 'Tensorrt. "NVIDIA TensorRT: Programmable Inference Accelerator." 2017. [Link](https://developer.nvidia.com/tensorrt)',
  'Wu18': 'Shuang Wu, Guoqi Li, Feng Chen, Luping Shi. "Training and Inference with Integers in Deep Neural Networks." International Conference on Learning Representations. 2018.',
  'Xie16': 'Saining Xie, Ross B Girshick, Piotr Dollár, Zhuowen Tu, Kaiming He. "Aggregated Residual Transformations for Deep Neural Networks." 2016.',
  'Zop16': 'Barret Zoph, V Quoc, Le. "Neural Architecture Search with Reinforcement Learning." 2016.',
  'Zop18': 'Barret Zoph, Vijay Vasudevan, Jonathon Shlens, Quoc V Le. "Learning transferable architectures for scalable image recognition." Proceedings of the IEEE conference on computer vision and pattern recognition. 2018.',
  'Ten18a': '"TensorFlow Graph Transform Tool." 2018. [Link](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms)',
  'Ada19': 'Andrew Adams, Karima Ma, Luke Anderson, Riyadh Baghdadi, Tzu-Mao Li, Michaël Gharbi, Benoit Steiner, Steven Johnson, Kayvon Fatahalian, Frédo Durand. "Learning to Optimize Halide with Tree Search and Random Programs." ACM Transactions on Graphics. 2019.',
  'Bag19': 'Riyadh Baghdadi, Jessica Ray, Malek Ben Romdhane, Emanuele Del Sozzo, Abdurrahman Akkas, Yunming Zhang, Patricia Suriana, Shoaib Kamil, Saman Amarasinghe. "Tiramisu: A Polyhedral Compiler for Expressing Fast and Portable Code." Proceedings of the 2019 IEEE/ACM International Symposium on Code Generation and Optimization (CGO). 2019.',
  'Cho20': 'Stephen Chou, Fredrik Kjolstad, Saman Amarasinghe. "Automatic Generation of Efficient Sparse Tensor Format Conversion Routines." 2020. [Link](https://arxiv.org/abs/2001.02609)',
  'DeM91': 'Richard A DeMillo, Edward W Krauser, Aditya P Mathur. "Compiler-Integrated Program Mutation." Proceedings of the Fifteenth Annual International Computer Software and Applications Conference. 1991.',
  'Har17': 'Kensho Hara, Hirokatsu Kataoka, Yutaka Satoh. "Learning Spatio-Temporal Features with 3D Residual Networks for Action Recognition." Proceedings of the IEEE International Conference on Computer Vision Workshops. 2017.',
  'Jia19b': 'Zhihao Jia, Oded Padon, James Thomas, Todd Warszawski, Matei Zaharia, Alex Aiken. "TASO: Optimizing Deep Learning Computation with Automatic Generation of Graph Substitutions." Proceedings of the 27th ACM Symposium on Operating Systems Principles (SOSP). 2019. [Link](/papers/taso/)',
  'Lav16': 'Andrew Lavin, Scott Gray. "Fast Algorithms for Convolutional Neural Networks." Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition. 2016.',
  'Li18': 'Tzu-Mao Li, Michaël Gharbi, Andrew Adams, Frédo Durand, Jonathan Ragan-Kelley. "Differentiable Programming for Image Processing and Deep Learning in Halide." ACM Transactions on Graphics. 2018.',
  'Li18a': 'Yuhong Li, Xiaofan Zhang, Deming Chen. "CSRNet: Dilated Convolutional Neural Networks for Understanding the Highly Congested Scenes." Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition. 2018.',
  'Liu19': 'Yizhi Liu, Yao Wang, Ruofei Yu, Mu Li, Vin Sharma, Yida Wang. "Optimizing CNN Model Inference on CPUs." 2019 USENIX Annual Technical Conference (USENIX ATC 19). 2019.',
  'Mul16': 'Ravi Teja Mullapudi, Andrew Adams, Dillon Sharlet, Jonathan Ragan-Kelley, Kayvon Fatahalian. "Automatically Scheduling Halide Image Processing Pipelines." ACM Transactions on Graphics. 2016.',
  'Ols16': 'Randal S Olson, Jason H Moore. "TPOT: A Tree-Based Pipeline Optimization Tool for Automating Machine Learning." Workshop on Automatic Machine Learning. 2016.',
  'OnnWeb': '"TensorFlow Backend for ONNX." [Link](https://github.com/onnx/onnx-tensorflow)',
  'Rag13': 'Jonathan Ragan-Kelley, Connelly Barnes, Andrew Adams, Sylvain Paris, Frédo Durand, Saman Amarasinghe. "Halide: A Language and Compiler for Optimizing Parallelism, Locality, and Recomputation in Image Processing Pipelines." Proceedings of the 34th ACM SIGPLAN Conference on Programming Language Design and Implementation (PLDI). 2013.',
  'Sch80': 'Jacob T Schwartz. "Fast Probabilistic Algorithms for Verification of Polynomial Identities." Journal of the ACM. 1980.',
  'Ste19': 'Christian Steinruecken, Emma Smith, David Janz, James Lloyd, Zoubin Ghahramani. "The Automatic Statistician." Automated Machine Learning. 2019.',
  'Sze14': 'Christian Szegedy, Wei Liu, Yangqing Jia, Pierre Sermanet, Scott E Reed, Dragomir Anguelov, Dumitru Erhan, Vincent Vanhoucke, Andrew Rabinovich. "Going Deeper with Convolutions." 2014. [Link](https://arxiv.org/abs/1409.4842)',
  'Sze16': 'Christian Szegedy, Vincent Vanhoucke, Sergey Ioffe, Jon Shlens, Zbigniew Wojna. "Rethinking the Inception Architecture for Computer Vision." Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition. 2016.',
  'Vas18': 'Nicolas Vasilache, Oleksandr Zinenko, Theodoros Theodoridis, Priya Goyal, Zachary DeVito, William S Moses, Sven Verdoolaege, Andrew Adams, Albert Cohen. "Tensor Comprehensions: Framework-Agnostic High-Performance Machine Learning Abstractions." 2018. [Link](https://arxiv.org/abs/1802.04730)',
  'Zhe20': 'Lianmin Zheng, Chengfan Jia, Minmin Sun, Zhao Wu, Cody Hao Yu, Ameer Haj-Ali, Yida Wang, Jun Yang, Danyang Zhuo, Koushik Sen. "Ansor: Generating High-Performance Tensor Programs for Deep Learning." 14th USENIX Symposium on Operating Systems Design and Implementation (OSDI 20). 2020.',
  'Zip79': 'Richard Zippel. "Probabilistic Algorithms for Sparse Polynomials." International Symposium on Symbolic and Algebraic Manipulation. 1979.',
  'Thi26': "\"Thinking Machines Lab. Inkling: Our Open-Weights Model.\" 2026. [Link](https://thinkingmachines.ai/news/introducing-inkling/)",
  'Ban26': "\"Banking.\" 2026. [Link](https://taubench.com/blog/tau-knowledge.html)",
  'Age26': "\"Agentic Knowledge Work Benchmark.\" AA-Briefcase Artificial Analysis. 2026. [Link](https://artificialanalysis.ai/evaluations/aa-briefcase)",
  'Aga20': "Alexandru Agache. \"Firecracker: Lightweight Virtualization for Serverless Applications.\" 17th USENIX Symposium on Networked Systems Design and Implementation (NSDI). 2020.",
  'Age26a': "\"Agents' Last Exam.\" 2026. [Link](https://agents-last-exam.org/leaderboard)",
  'Ans24': "Jason Ansel. \"PyTorch 2: Faster Machine Learning Through Dynamic Python Bytecode Transformation and Graph Compilation.\" Proceedings of the 29th ACM International Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS). 2024. [DOI](https://doi.org/10.1145/3620665.3640366)",
  'Ant25': "Anthropic. \"Claude's Extended Thinking.\" 2025. [Link](https://www.anthropic.com/research/visible-extended-thinking)",
  'Int25': "\"Introducing Claude 4.\" 2025. [Link](https://www.anthropic.com/news/claude-4)",
  'Art26': "\"Artificial Analysis.\" 2026. [Link](https://artificialanalysis.ai/)",
  'Art26a': "\"Artificial Analysis Long Context Reasoning (AA-LCR).\" Artificial Analysis. 2026. [Link](https://artificialanalysis.ai/evaluations/artificial-analysis-long-context-reasoning)",
  'Bah14': "Dzmitry Bahdanau, Kyunghyun Cho, Yoshua Bengio. \"Neural Machine Translation by Jointly Learning to Align and Translate.\" cs.CL. 2014. [Link](https://arxiv.org/abs/1409.0473)",
  'Ban26a': "Chaithanya Bandi. \"MCP-Atlas: A Large-Scale Benchmark for Tool-Use Competency with Real MCP Servers.\" cs.SE. 2026.",
  'Bet26': "\"Better MoE Model Inference with Warp Decode.\" Cursor. 2026. [Link](https://cursor.com/blog/warp-decode)",
  'Che26': "Liang Chen. \"BabyVision: Visual Reasoning Beyond Language.\" 2026. [Link](https://arxiv.org/abs/2601.06521)",
  'Che26a': "Yutian Chen. \"FlashKDA: Flash Kimi Delta Attention.\" 2026. [Link](https://github.com/MoonshotAI/FlashKDA)",
  'Cod26': "Claude Code, Anthropic. 2026. [Link](https://docs.anthropic.com/en/docs/claude-code)",
  'Fab26': "Claude Fable. \"Anthropic.\" 2026. [Link](https://www.anthropic.com/news/claude-fable-5-mythos-5)",
  'Opu26': "Claude Opus. \"Anthropic.\" 2026. [Link](https://www.anthropic.com/news/claude-opus-4-8)",
  'Son26': "Claude Sonnet. \"Anthropic.\" 2026. [Link](https://www-cdn.anthropic.com/283ef97c476cf442c91d9a37d5b214242a55bb92/Claude%20Sonnet%205%20System%20Card.pdf)",
  'Son26a': "Claude Sonnet. \"Anthropic.\" 2026. [Link](https://www.anthropic.com/news/claude-sonnet-5)",
  'Cod26a': "\"Codex.\" 2026. [Link](https://github.com/openai/codex)",
  'Val26': "\"Vals AI.\" 2026. [Link](https://www.vals.ai/benchmarks/corp_fin_v2)",
  'Cub26': "Cublas. \"NVIDIA.\" 2026. [Link](https://developer.nvidia.com/cublas)",
  'Dai24': "Damai Dai. \"DeepSeekMoE: Towards Ultimate Expert Specialization in Mixture-of-Experts Language Models.\" cs.CL. 2024. [Link](https://arxiv.org/abs/2401.06066)",
  'Dao24': "Tri Dao, Albert Gu. \"Transformers are SSMs: Generalized Models and Efficient Algorithms Through Structured State Space Duality.\" 2024. [Link](https://doi.org/10.48550/arXiv.2405.21060)",
  'Dao26': "A I Dao, Lab. \"ReplaySSM: Cache SSM Inputs, Not State.\" 2026. [Link](https://tridao.me/blog/2026/replayssm/)",
  'Yan17': "N Yann, Dauphin. \"Language Modeling with Gated Convolutional Networks.\" Proceedings of the 34th International Conference on Machine Learning. Proceedings of Machine Learning Research. 2017. [Link](https://proceedings.mlr.press/v70/dauphin17a.html)",
  'De24': "Soham De. \"Mixing Gated Linear Recurrences with Local Attention for Efficient Language Models.\" 2024. [Link](https://arxiv.org/abs/2402.19427)",
  'Dee24': "Deepseek-Ai. \"DeepSeek-V2: A Strong, Economical, and Efficient Mixture-of-Experts Language Model.\" cs.CL. 2024. [Link](https://arxiv.org/abs/2405.04434)",
  'Dee26': "Deepseek-Ai. \"DeepSeek-V4: Towards Highly Efficient Million-Token Context Intelligence.\" arXiv preprint. 2026.",
  'Dee24a': "Deepseek-Ai. DeepSeek-V3 Technical Report. 2024. [Link](https://arxiv.org/abs/2412.19437)",
  'Ela26': "Venmugil Elango. \"LatentMoE: Toward Optimal Accuracy per FLOP and Parameter in Mixture of Experts.\" 2026. [Link](https://arxiv.org/abs/2601.18089)",
  'Fed22': "William Fedus, Barret Zoph, Noam Shazeer. \"Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity.\" Journal of Machine Learning Research. 2022.",
  'Fen25': "Weiqi Feng. \"Optimus: Accelerating Large-Scale Multi-Modal LLM Training by Bubble Exploitation.\" 2025 USENIX Annual Technical Conference (USENIX ATC 25). 2025. [Link](https://www.usenix.org/conference/atc25/presentation/feng)",
  'Val26a': "\"Vals AI.\" 2026. [Link](https://www.vals.ai/benchmarks/fabv2)",
  'Fro26': "Frontierswe. 2026. [Link](https://www.frontierswe.com/)",
  'Fu24': "Chaoyou Fu. \"Video-MME: The First-Ever Comprehensive Evaluation Benchmark of Multi-modal LLMs in Video Analysis.\" 2024. [Link](https://arxiv.org/abs/2405.21075)",
  'GlmWeb': "\"GLM.\"",
  'Z26': "Z. 2026. [Link](https://z.ai/blog/glm-5.2)",
  'Ope26': "Openai. 2026. [Link](https://openai.com/index/introducing-gpt-5-5/)",
  'Sol26': "\"Sol. OpenAI.\" 2026. [Link](https://openai.com/index/previewing-gpt-5-6-sol/)",
  'Guo25': "Daya Guo. \"DeepSeek-R1 incentivizes reasoning in LLMs through reinforcement learning.\" Nature. 2025. [Link](http://dx.doi.org/10.1038/s41586-025-09422-z)",
  'Guo25a': "Wentao Guo. \"SonicMoE: Accelerating MoE with IO and Tile-aware Optimizations.\" 2025. [Link](https://arxiv.org/abs/2512.14080)",
  'Har26': "Lab Harvey. \"Legal Agent Benchmark.\" 2026. [Link](https://www.harvey.ai/blog/introducing-harveys-legal-agent-benchmark)",
  'He15': "Kaiming He. \"Deep Residual Learning for Image Recognition.\" 2015. [Link](https://arxiv.org/abs/1512.03385)",
  'Age26b': "Hermes Agent. \"Nous Research.\" 2026. [Link](https://hermes-agent.nousresearch.com/docs/)",
  'Hof22': "Jordan Hoffmann. \"Training Compute-Optimal Large Language Models.\" cs.CL. 2022. [Link](https://arxiv.org/abs/2203.15556)",
  'Hu24': "Shengding Hu, Yuge Tu, Xu Han. \"MiniCPM: Unveiling the Potential of Small Language Models with Scalable Training Strategies.\" cs.CL. 2024.",
  'Hua26': "Ailin Huang, Ang Li, Aobo Kong. \"Step 3.5 Flash: Open Frontier-Level Intelligence with 11B Active Parameters.\" arXiv preprint. 2026.",
  'Hua19': "Yanping Huang. \"Gpipe: Efficient training of giant neural networks using pipeline parallelism.\" Advances in neural information processing systems. 2019.",
  'Ben18': "Jacob Benoit. \"Quantization and Training of Neural Networks for Efficient Integer-Arithmetic-Only Inference.\" Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition (CVPR). 2018.",
  'Sam23': "Ade Sam, Jacobs. \"DeepSpeed Ulysses: System Optimizations for Enabling Training of Extreme Long Sequence Transformer Models.\" 2023. [Link](https://arxiv.org/abs/2309.14509)",
  'Jia26': "Peijie Jiang. \"PowLU: An Activation Function for Stable Pre-Training of LLMs.\" cs.CL. 2026. [Link](https://arxiv.org/abs/2605.25704)",
  'Job26': "Jobbench. \"Aligning Agent Work with Human Will.\" 2026. [Link](https://job-bench.github.io/)",
  'Kel24': "Jordan Keller. \"Muon: An Optimizer for Hidden Layers in Neural Networks.\" 2024. [Link](https://kellerjordan.github.io/posts/muon/)",
  'Kap20': "Jared Kaplan. \"Scaling Laws for Neural Language Models.\" 2020. [Link](https://arxiv.org/abs/2001.08361)",
  'Kat20': "Angelos Katharopoulos. \"Transformers are RNNs: Fast Autoregressive Transformers with Linear Attention.\" Proceedings of ICML. 2020. [Link](https://proceedings.mlr.press/v119/katharopoulos20a.html)",
  'Kim26': "Cli Kimi, A I Moonshot. 2026. [Link](https://www.kimi.com/code)",
  'Tea26': "Kimi Team. \"Attention Residuals.\" Preprint. 2026.",
  'Tea25': "Kimi Team, K Kimi. \"Open Agentic Intelligence.\" 2025.",
  'Kim26a': "\"Kimi K2.5: Visual Agentic Intelligence.\" arXiv preprint. 2026.",
  'Tea26a': "Kimi Team, K Kimi. \"Open Frontier Intelligence. Moonshot AI.\" 2026. [Link](https://www.kimi.com/blog/kimi-k3)",
  'Tea25a': "Kimi Team. \"Kimi-vl technical report.\" arXiv preprint. 2025.",
  'Tea26b': "Kimi Team. \"PerceptionBench: Evaluating Atomic Visual Perception in Multimodal Large Language Models.\" Moonshot AI. 2026. [Link](https://www.kimi.com/blog/perception-bench)",
  'Tea25b': "Kimi Team. \"Linear: An Expressive, Efficient Attention Architecture.\" cs.CL. 2025.",
  'Lat21': "Chris Lattner. \"MLIR: Scaling Compiler Infrastructure for Domain Specific Computation.\" 2021 IEEE/ACM International Symposium on Code Generation and Optimization. 2021. [DOI](https://doi.org/10.1109/CGO51591.2021.9370308)",
  'Val26b': "\"Vals AI.\" 2026. [Link](https://www.vals.ai/benchmarks/legal_research)",
  'Lep20': "Dmitry Lepikhin. \"Gshard: Scaling giant models with conditional computation and automatic sharding.\" arXiv preprint. 2020.",
  'Lew21': "Mike Lewis. \"BASE Layers: Simplifying Training of Large, Sparse Models.\" Proceedings of ICML. 2021.",
  'Li20': "Huiba Li. \"DADI: Block-Level Image Service for Agile and Elastic Application Deployment.\" 2020 USENIX Annual Technical Conference (USENIX ATC). 2020.",
  'LiWeb': "Junlong Li. \"The Tool Decathlon: Benchmarking Language Agents for Diverse, Realistic, and Long-Horizon Task Execution.\" cs.CL.",
  'Li26': "Yuetai Li. \"JobBench: Aligning Agent Work With Human Will.\" cs.AI. 2026.",
  'Li25': "Yuhui Li. \"EAGLE-3: Scaling up Inference Acceleration of Large Language Models via Training-Time Test.\" cs.CL. 2025. [Link](https://arxiv.org/abs/2503.01840)",
  'Liu23': "Hao Liu, Matei Zaharia, Pieter Abbeel. \"Ring Attention with Blockwise Transformers for Near-Infinite Context.\" cs.CL. 2023. [Link](https://arxiv.org/abs/2310.01889)",
  'Liu25': "Jingyuan Liu. \"Muon is Scalable for LLM Training.\" 2025. [Link](https://arxiv.org/abs/2502.16982)",
  'Lea26': "Lmarena Leaderboard, Lmarena. 2026. [Link](https://lmarena.ai/leaderboard)",
  'Lu25': "Kevin Lu. \"Thinking Machines Lab.\" Thinking Machines Lab: Connectionism. On-policy distillation. 2025. [Link](https://thinkingmachines.ai/blog/on-policy-distillation/)",
  'Lyu26': "Bohan Lyu. \"MLS-Bench: A Holistic and Rigorous Assessment of AI Systems on Building Better AI.\" 2026.",
  'Mar18': "Eric Martin, Chris Cundy. \"Parallelizing Linear Recurrent Neural Nets Over Sequence Length.\" Proceedings of ICLR. 2018. [Link](https://openreview.net/forum?id=HyUNwulC-)",
  'Mer26': "Mike A Merrill. \"Terminal-Bench: Benchmarking Agents on Hard, Realistic Tasks in Command Line Interfaces.\" arXiv preprint. 2026.",
  'Mil18': "Maxim Milakov, Natalia Gimelshein. \"Online normalizer calculation for softmax.\" cs.PF. 2018. [Link](https://arxiv.org/abs/1805.02867)",
  'Nan10': "Inc Nangate. \"Nangate 45nm Open Cell Library.\" _v2010_12. Donated to and distributed by the Silicon Integration Initiative (Si2. 2010. [Link](https://si2.org/open-cell-library/.VersionPDKv1_3)",
  'Nar21': "Deepak Narayanan. \"Efficient large-scale language model training on gpu clusters using megatron-lm.\" Proceedings of the international conference for high performance computing, networking, storage and analysis. 2021.",
  'NccWeb': "\"NCCL: The NVIDIA Collective Communications Library.\" [Link](https://developer.nvidia.com/nccl)",
  'Ope25': "Openai. \"Introducing OpenAI o3 and o4-mini.\" 2025. [Link](https://openai.com/index/introducing-o3-and-o4-mini/)",
  'Ope24': "Openai. \"Learning to Reason with LLMs.\" 2024. [Link](https://openai.com/index/learning-to-reason-with-llms/)",
  'Ope25a': "\"OpenAI Harmony Response Format.\" 2025. [Link](https://github.com/openai/harmony)",
  'Ope26a': "Openclaw, Openclaw. 2026. [Link](https://docs.openclaw.ai/)",
  'Ops26': "Krista Opsahl-Ong. \"OfficeQA Pro: An Enterprise Benchmark for End-to-End Grounded Reasoning.\" 2026.",
  'Ouy25': "Linke Ouyang. \"OmniDocBench: Benchmarking Diverse PDF Document Parsing with Comprehensive Annotations.\" 2025. [Link](https://arxiv.org/abs/2412.07626)",
  'Pas19': "Adam Paszke. \"PyTorch: An Imperative Style, High-Performance Deep Learning Library.\" 2019.",
  'Pat25': "Tejal Patwardhan. \"GDPval: Evaluating AI Model Performance on Real-World Economically Valuable Tasks.\" 2025. [Link](https://arxiv.org/abs/2510.04374)",
  'Pen25': "Bo Peng. \"Goose\" with Expressive Dynamic State Evolution.\" RWKV-7 cs.CL. 2025.",
  'Pen23': "Bowen Peng. \"Yarn: Efficient context window extension of large language models.\" arXiv preprint. 2023.",
  'Pha25': "Long Phan. \"Humanity's Last Exam.\" 2025. [Link](https://arxiv.org/abs/2501.14249)",
  'Pos26': "Posttrainbench. 2026. [Link](https://posttrainbench.com/)",
  'Pro26': "Programbench, A I Vals. 2026. [Link](https://www.vals.ai/benchmarks/programbench)",
  'Qin24': "Ruoyu Qin. \"Mooncake: A KVCache-centric Disaggregated Architecture for LLM Serving.\" cs.DC. 2024.",
  'Qin24a': "Zhen Qin. \"HGRN2: Gated Linear RNNs with State Expansion.\" cs.CL. 2024. [Link](https://arxiv.org/abs/2404.07904)",
  'Qiu26': "Haiquan Qiu, Quanming Yao. \"Why Low-Precision Transformer Training Fails: An Analysis on Flash Attention.\" International Conference on Learning Representations (ICLR). 2026.",
  'Qiu25': "Zihan Qiu. \"Gated Attention for Large Language Models: Non-linearity, Sparsity, and Attention-Sink-Free.\" cs.CL. 2025.",
  'Raj20': "Samyam Rajbhandari. \"Zero: Memory optimizations toward training trillion parameter models.\" SC20: International Conference for High Performance Computing, Networking, Storage and Analysis. 2020.",
  'Rei24': "David Rein. \"Gpqa: A graduate-level google-proof q&a benchmark.\" First Conference on Language Modeling. 2024.",
  'Rob25': "Jonathan Roberts. \"ZeroBench: An Impossible Visual Benchmark for Contemporary Large Multimodal Models.\" 2025. [Link](https://arxiv.org/abs/2502.09696)",
  'Dar23': "Bita Darvish, Rouhani. \"Microscaling Data Formats for Deep Learning.\" arXiv preprint. 2023.",
  'Sam26': "Alexander Samarin. \"LK Losses: Direct Acceptance Rate Optimization for Speculative Decoding.\" 2026. [Link](https://arxiv.org/abs/2602.23881)",
  'Sch21': "Imanol Schlag, Kazuki Irie, Jürgen Schmidhuber. \"Linear Transformers Are Secretly Fast Weight Programmers.\" Proceedings of ICML. 2021. [Link](https://proceedings.mlr.press/v139/schlag21a.html)",
  'Sha26': "Manasi Sharma. \"ResearchRubrics: A Benchmark of Prompts and Rubrics For Evaluating Deep Research Agents.\" The Fourteenth International Conference on Learning Representations. 2026. [Link](https://openreview.net/forum?id=ErnvfmSX0P)",
  'Sha20': "Noam Shazeer. \"GLU Variants Improve Transformer.\" 2020. [Link](https://arxiv.org/abs/2002.05202)",
  'She26': "Daniel Shepard, Robin Salimans. \"AutomationBench.\" cs.AI. 2026.",
  'Shi26': "Kean Shi. \"SaaS-Bench: Can Computer-Use Agents Leverage Real-World SaaS to Solve Professional Workflows?.\" cs.AI. 2026. [Link](https://arxiv.org/abs/2605.15777)",
  'Ben25': "F Benjamin, Spector. \"ThunderKittens: Simple, Fast, and Adorable Kernels.\" The Thirteenth International Conference on Learning Representations. 2025. [Link](https://openreview.net/forum?id=0fJfVOSUra)",
  'Su26': "Jianlin Su. \"Travels in MoE: 6. Promoting Load Balance via Optimal Assignment.\" Blog post in Chinese. 2026. [Link](https://spaces.ac.cn/archives/11619)",
  'Sun26': "Hanchi Sun. \"Expert Threshold Routing for Autoregressive Language Modeling with Dynamic Computation Allocation and Load Balancing.\" cs.AI. 2026.",
  'Sun25': "Weigao Sun. \"LASP-2: Rethinking Sequence Parallelism for Linear Attention and Its Hybrid.\" 2025. [Link](https://arxiv.org/abs/2502.07563)",
  'Sun24': "Weigao Sun. \"Linear Attention Sequence Parallelism.\" 2024. [Link](https://arxiv.org/abs/2404.02882)",
  'Sun26a': "Yiyou Sun. \"Agents' Last Exam.\" cs.AI. 2026. [Link](https://arxiv.org/abs/2606.05405)",
  'Sun25a': "Yuan Sun. \"Binary-Integer-Programming Based Algorithm for Expert Load Balancing in Mixture-of-Experts Models.\" 2025.",
  'Mar26': "Swe Marathon. 2026. [Link](https://www.swe-marathon.org/)",
  'Sca25': "\"Scaling Reinforcement Learning with LLMs.\" Kimi Team. Kimi k. cs.AI. 2025. [Link](https://arxiv.org/abs/2501.12599)",
  'The26': "\"The Tool Decathlon: Benchmarking Language Agents for Diverse, Realistic, and Long-Horizon Task Execution.\" 2026. [Link](https://toolathlon.xyz/introduction)",
  'Tia24': "Minyang Tian. \"SciCode: A Research Coding Benchmark Curated by Scientists.\" cs.AI. 2024. [Link](https://arxiv.org/abs/2407.13168)",
  'Til19': "Philippe Tillet, Hsiang-Tsung, David Kung, Cox. \"Triton: An Intermediate Language and Compiler for Tiled Neural Network Computations.\" Proceedings of the 3rd ACM SIGPLAN International Workshop on Machine Learning and Programming Languages (MAPL). 2019.",
  'Pre26': "\"Preliminary Assessment of Kimi K3's Cyber Capabilities.\" 2026. [Link](https://www.aisi.gov.uk/blog/preliminary-assessment-of-kimi-k3s-cyber-capabilities)",
  'Val26c': "A I Vals, A I Vals. 2026. [Link](https://www.vals.ai/)",
  'Vas17': "Ashish Vaswani. \"Attention is All you Need.\" Advances in NeurIPS. 2017. [Link](https://proceedings.neurips.cc/paper_files/paper/2017/file/3f5ee243547dee91fbd053c1c4a845aa-Paper.pdf)",
  'Ved25': "Nikhita Vedula. \"DeepSearchQA: Bridging the Comprehensiveness Gap for Deep Research Agents.\" 2025. [Link](https://storage.googleapis.com/deepmind-media/DeepSearchQA/DeepSearchQA_benchmark_paper.pdf)",
  'Vid26': "Bertie Vidgen. \"APEX-Agents.\" cs.CL. 2026.",
  'Wan24': "Ke Wang. \"Measuring Multimodal Mathematical Reasoning with MATH-Vision Dataset.\" Advances in NeurIPS. 2024. [Link](https://proceedings.neurips.cc/paper_files/paper/2024/file/ad0edc7d5fa1a783f063646968b7315b-Paper-Datasets_and_Benchmarks_Track.pdf)",
  'Wan25': "Lei Wang. \"TileLang: A Composable Tiled Programming Model for AI Systems.\" arXiv preprint. 2025. [Link](https://arxiv.org/abs/2504.17577)",
  'Wan24a': "Zirui Wang. \"CharXiv: Charting Gaps in Realistic Chart Understanding in Multimodal LLMs.\" cs.CL. 2024. [Link](https://arxiv.org/abs/2406.18521)",
  'Wei25': "Jason Wei. \"BrowseComp: A Simple Yet Challenging Benchmark for Browsing Agents.\" cs.CL. 2025. [Link](https://arxiv.org/abs/2504.12516)",
  'Wei26': "Xinming Wei. \"UltraEP: Unleash MoE Training and Inference on Rack-Scale Nodes with Near-Optimal Load Balancing.\" cs.DC. 2026. [Link](https://arxiv.org/abs/2606.04101)",
  'Wu25': "Zijian Wu. \"MCPMark: A benchmark for stress-testing realistic and comprehensive mcp use.\" arXiv preprint. 2025.",
  'Xia26': "B Xiao. \"MiMo-V2-Flash Technical Report.\" arXiv preprint. 2026.",
  'XiaWeb': "\"Xiaomi MiMo Team.\" MiMo-V2.5-Pro. [Link](https://huggingface.co/collections/XiaomiMiMo/mimo-v25.2026)",
  'Xie25': "Tianbao Xie. \"Introducing OSWorld-Verified.\" xlang.ai. 2025. [Link](https://xlang.ai/blog/osworld-verified)",
  'Yan26': "Zijie Yan. \"Scalable Training of Mixture-of-Experts Models with Megatron Core.\" cs.DC. 2026. [Link](https://arxiv.org/abs/2603.07685)",
  'Yan25': "Songlin Yang, Jan Kautz, Ali Hatamizadeh. \"Gated Delta Networks: Improving Mamba2 with Delta Rule.\" Proceedings of ICLR. 2025. [Link](https://openreview.net/forum?id=r8H7xhYPwz)",
  'Yan24': "Songlin Yang, Yu Zhang. \"FLA: A Triton-Based Library for Hardware-Efficient Implementations of Linear Attention Mechanism.\" 2024. [Link](https://github.com/fla-org/flash-linear-attention)",
  'Yan24a': "Songlin Yang. \"Gated Linear Attention Transformers with Hardware-Efficient Training.\" Proceedings of ICML. PMLR. 2024.",
  'Yan24b': "Songlin Yang. \"Parallelizing Linear Transformers with the Delta Rule over Sequence Length.\" Proceedings of NeurIPS. 2024.",
  'Wan25a': "Yaoyu Wang. \"Context Parallelism for DeltaNet.\" 2025. [Link](https://yywangcs.notion.site/DeltaNet-2a9fc9f5d8058013a498)",
  'Yua26': "Mengqi Yuan. \"OSWorld2.0: Benchmarking Computer Use Agents on Long-Horizon Real-World Tasks.\" cs.AI. 2026. [Link](https://arxiv.org/abs/2606.29537)",
  'Yue24': "Xiang Yue. \"MMMU-Pro: A More Robust Multi-discipline Multimodal Understanding Benchmark.\" cs.CL. 2024. [Link](https://arxiv.org/abs/2409.02813)",
  'Zen26': "Aohan Zeng. \"GLM-5: from Vibe Coding to Agentic Engineering.\" 2026. [Link](https://arxiv.org/abs/2602.15763)",
  'Zha19': "Biao Zhang, Rico Sennrich. \"Root mean square layer normalization.\" Advances in NeurIPS. 2019.",
  'ZhaWeb': "Chenggang Zhao. \"DeepEP: an efficient expert-parallel communication library.\" [Link](https://github.com/deepseek-ai/DeepEP.2025)",
  'Zha25': "Yilun Zhao. \"MMVU: Measuring Expert-Level Multi-Discipline Video Understanding.\" Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR). 2025.",
  'Zho26': "Runjie Zhou. \"WorldVQA: Measuring Atomic World Knowledge in Multimodal Large Language Models.\" 2026. [Link](https://arxiv.org/abs/2602.02537)",
  'Zhu26': "Jian Zhu. \"SpreadsheetBench 2: Evaluating Agents on End-to-End Business Spreadsheet Workflows.\" cs.SE. 2026.",
}

export default defineUserConfig({
  locales: {
    '/': {
      lang: 'zh-CN',
      title: 'ASa Book',
      description: 'csdiy 与论文文档',
    },
    '/en/': {
      lang: 'en-US',
      title: 'ASa Book',
      description: 'Notes on self-directed study and papers',
    },
    '/ja/': {
      lang: 'ja-JP',
      title: 'ASa Book',
      description: '自主学習と論文についてのノート',
    },
  },

  theme: plumeTheme({
    docsRepo: 'https://github.com/pare1lel/asabook',
    social: [
      { icon: 'github', link: 'https://github.com/pare1lel/asabook' },
      { icon: 'bilibili', link: 'https://space.bilibili.com/349394806' },
    ],
    navbarSocialInclude: ['github', 'bilibili'],
    locales: {
      '/': {
        selectLanguageName: '简体中文',
        navbar: [
          { text: 'csdiy', link: '/csdiy/cse291a/', activeMatch: '^/csdiy/' },
          { text: 'papers', link: '/papers/taso/', activeMatch: '^/papers/' },
        ],
        collections: [
          {
            type: 'doc',
            title: 'vndb',
            dir: 'vndb',
            linkPrefix: '/vndb/',
            sidebar: [
              {
                text: 'VNDB',
                collapsed: false,
                items: ['intro'],
              },
            ],
          },
          {
            type: 'doc',
            title: 'csdiy',
            dir: 'csdiy',
            linkPrefix: '/csdiy/',
            sidebar: [
              {
                text: 'AoPS',
                collapsed: true,
                items: ['aops', 'tst26-p18', 'isl19-a5', 'tst26-p12'],
              },
              {
                text: 'CSE 291A',
                collapsed: false,
                items: ['cse291a', 'cse291a-week1', 'cse291a-week2', 'cse291a-week3'],
              },
            ],
          },
          {
            type: 'doc',
            title: 'papers',
            dir: 'papers',
            linkPrefix: '/papers/',
            sidebar: [
              {
                text: '论文',
                collapsed: false,
                items: ['taso', 'pet', 'kimi-k3'],
              },
            ],
          },
        ],
        footer: {
          message: '基于 VuePress 与 Plume 主题构建',
          copyright: 'Copyright © 2026 ASa Book',
        },
      },
      '/en/': {
        selectLanguageName: 'English',
        navbar: [
          { text: 'csdiy', link: '/en/csdiy/cse291a/', activeMatch: '^/en/csdiy/' },
          { text: 'papers', link: '/en/papers/taso/', activeMatch: '^/en/papers/' },
        ],
        collections: [
          {
            type: 'doc',
            title: 'vndb',
            dir: 'vndb',
            linkPrefix: '/vndb/',
            sidebar: [
              {
                text: 'VNDB',
                collapsed: false,
                items: ['intro'],
              },
            ],
          },
          {
            type: 'doc',
            title: 'csdiy',
            dir: 'csdiy',
            linkPrefix: '/csdiy/',
            sidebar: [
              {
                text: 'AoPS',
                collapsed: true,
                items: ['aops', 'tst26-p18', 'isl19-a5', 'tst26-p12'],
              },
              {
                text: 'CSE 291A',
                collapsed: false,
                items: ['cse291a', 'cse291a-week1', 'cse291a-week2', 'cse291a-week3'],
              },
            ],
          },
          {
            type: 'doc',
            title: 'papers',
            dir: 'papers',
            linkPrefix: '/papers/',
            sidebar: [
              {
                text: 'Papers',
                collapsed: false,
                items: ['taso', 'pet', 'kimi-k3'],
              },
            ],
          },
        ],
        footer: {
          message: 'Built with VuePress and the Plume theme',
          copyright: 'Copyright © 2026 ASa Book',
        },
      },
      '/ja/': {
        selectLanguageName: '日本語',
        navbar: [
          { text: 'csdiy', link: '/ja/csdiy/cse291a/', activeMatch: '^/ja/csdiy/' },
          { text: 'papers', link: '/ja/papers/taso/', activeMatch: '^/ja/papers/' },
        ],
        collections: [
          {
            type: 'doc',
            title: 'vndb',
            dir: 'vndb',
            linkPrefix: '/vndb/',
            sidebar: [
              {
                text: 'VNDB',
                collapsed: false,
                items: ['intro'],
              },
            ],
          },
          {
            type: 'doc',
            title: 'csdiy',
            dir: 'csdiy',
            linkPrefix: '/csdiy/',
            sidebar: [
              {
                text: 'AoPS',
                collapsed: true,
                items: ['aops', 'tst26-p18', 'isl19-a5', 'tst26-p12'],
              },
              {
                text: 'CSE 291A',
                collapsed: false,
                items: ['cse291a', 'cse291a-week1', 'cse291a-week2', 'cse291a-week3'],
              },
            ],
          },
          {
            type: 'doc',
            title: 'papers',
            dir: 'papers',
            linkPrefix: '/papers/',
            sidebar: [
              {
                text: '論文',
                collapsed: false,
                items: ['taso', 'pet', 'kimi-k3'],
              },
            ],
          },
        ],
        footer: {
          message: 'VuePress と Plume テーマで構築',
          copyright: 'Copyright © 2026 ASa Book',
        },
      },
    },
    lastUpdated: false,
    editLink: false,
    changelog: true,
    contributors: false,
    plugins: { git: true },
    codeHighlighter: {
      langs: [pseudocodeLanguage],
      renderIndentGuides: true,
      colorizedBrackets: true
    },
    markdown: {
      abbr: paperAbbreviations,
      annotation: true,
      mermaid: true,
    },
  }),

  bundler: viteBundler(),
})
